### ISSUE TITLE
Licensing information missing

### ISSUE THREAD

**Issue by hroncok** [Sanqui/pyvo-twitter#1]
Please add a LICENSE file with the license text and info to the README.

**Comment by Sanqui** [comment]
Do you think it's fine for me to use MIT and make it copyright "the Pyvo organizers", just like [pyvodb](https://github.com/pyvec/pyvodb/blob/master/LICENSE)?

**Comment by hroncok** [comment]
If you identify as Pyvo organizer, I think it's fine.

**Comment by Sanqui** [comment]
I do now, if my code will be announcing them!  :)
